### ISSUE TITLE
Using OData endpoints with Authorization access token

### ISSUE THREAD

**Issue by prokilogrammer** [thuld/CrmRestKit#1]
Thanks for the wonderful library. Do you know if I can authorize OData endpoints (and subsequently your library) using an OAuth2 access token that I receive from Active Directory? I know how to get the access token, but even if I pass the token thru HTTP Bearer Authorization header to OData endpoints, these requests don't get authorized.

**Comment by thuld** [comment]
Hello Sanath, 

I would assume that this will not work but I am not an export on this topic. With the new "WebAPI" your neede the clientId and the redirectURL", take a look at the new WebAPI:
http://blogs.msdn.com/b/crm/archive/2015/06/10/web-api-preview-documentation-released.aspx

And the article outlines how you register you app:
https://msdn.microsoft.com/en-us/dynamics/crm/mt149065.aspx

Daniel

**Comment by prokilogrammer** [comment]
Hey Daniel,

Thanks for the reply. Yeah, I think dynamics crm won't work without a redirect url. I was trying to write a server-side script that doesn't run on the browser. So I tried using the plain clientId & clientSecret based OAuth flow, but it doesn't work. Thanks for the pointers.
